version: '<no value>'



services:

  mariadb:
    image: bitnami/mariadb:11
    environment:
      - "MARIADB_PORT_NUMBER=3306"
      - "MARIADB_ROOT_USER=root"
    user: "999"
    
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: "2.0"
          memory: 2000MB
      update_config:
        parallelism: 1
        delay: 10m
